package cn.mercury9.omms.connect.desktop.ui.theme.aqua

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object AquaThemeColors{
    val primaryLight = Color(0xFF006A6A)
    val onPrimaryLight = Color(0xFFFFFFFF)
    val primaryContainerLight = Color(0xFF9CF1F0)
    val onPrimaryContainerLight = Color(0xFF002020)
    val secondaryLight = Color(0xFF4A6363)
    val onSecondaryLight = Color(0xFFFFFFFF)
    val secondaryContainerLight = Color(0xFFCCE8E7)
    val onSecondaryContainerLight = Color(0xFF051F1F)
    val tertiaryLight = Color(0xFF4B607C)
    val onTertiaryLight = Color(0xFFFFFFFF)
    val tertiaryContainerLight = Color(0xFFD3E4FF)
    val onTertiaryContainerLight = Color(0xFF041C35)
    val errorLight = Color(0xFFBA1A1A)
    val onErrorLight = Color(0xFFFFFFFF)
    val errorContainerLight = Color(0xFFFFDAD6)
    val onErrorContainerLight = Color(0xFF410002)
    val backgroundLight = Color(0xFFF4FBFA)
    val onBackgroundLight = Color(0xFF161D1D)
    val surfaceLight = Color(0xFFF4FBFA)
    val onSurfaceLight = Color(0xFF161D1D)
    val surfaceVariantLight = Color(0xFFDAE5E4)
    val onSurfaceVariantLight = Color(0xFF3F4948)
    val outlineLight = Color(0xFF6F7979)
    val outlineVariantLight = Color(0xFFBEC9C8)
    val scrimLight = Color(0xFF000000)
    val inverseSurfaceLight = Color(0xFF2B3231)
    val inverseOnSurfaceLight = Color(0xFFECF2F1)
    val inversePrimaryLight = Color(0xFF80D5D4)
    val surfaceDimLight = Color(0xFFD5DBDA)
    val surfaceBrightLight = Color(0xFFF4FBFA)
    val surfaceContainerLowestLight = Color(0xFFFFFFFF)
    val surfaceContainerLowLight = Color(0xFFEFF5F4)
    val surfaceContainerLight = Color(0xFFE9EFEE)
    val surfaceContainerHighLight = Color(0xFFE3E9E9)
    val surfaceContainerHighestLight = Color(0xFFDDE4E3)

    val primaryLightMediumContrast = Color(0xFF004B4B)
    val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
    val primaryContainerLightMediumContrast = Color(0xFF238181)
    val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryLightMediumContrast = Color(0xFF2E4747)
    val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightMediumContrast = Color(0xFF5F7979)
    val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryLightMediumContrast = Color(0xFF2F445F)
    val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightMediumContrast = Color(0xFF617693)
    val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
    val errorLightMediumContrast = Color(0xFF8C0009)
    val onErrorLightMediumContrast = Color(0xFFFFFFFF)
    val errorContainerLightMediumContrast = Color(0xFFDA342E)
    val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
    val backgroundLightMediumContrast = Color(0xFFF4FBFA)
    val onBackgroundLightMediumContrast = Color(0xFF161D1D)
    val surfaceLightMediumContrast = Color(0xFFF4FBFA)
    val onSurfaceLightMediumContrast = Color(0xFF161D1D)
    val surfaceVariantLightMediumContrast = Color(0xFFDAE5E4)
    val onSurfaceVariantLightMediumContrast = Color(0xFF3B4544)
    val outlineLightMediumContrast = Color(0xFF576161)
    val outlineVariantLightMediumContrast = Color(0xFF737D7C)
    val scrimLightMediumContrast = Color(0xFF000000)
    val inverseSurfaceLightMediumContrast = Color(0xFF2B3231)
    val inverseOnSurfaceLightMediumContrast = Color(0xFFECF2F1)
    val inversePrimaryLightMediumContrast = Color(0xFF80D5D4)
    val surfaceDimLightMediumContrast = Color(0xFFD5DBDA)
    val surfaceBrightLightMediumContrast = Color(0xFFF4FBFA)
    val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightMediumContrast = Color(0xFFEFF5F4)
    val surfaceContainerLightMediumContrast = Color(0xFFE9EFEE)
    val surfaceContainerHighLightMediumContrast = Color(0xFFE3E9E9)
    val surfaceContainerHighestLightMediumContrast = Color(0xFFDDE4E3)

    val primaryLightHighContrast = Color(0xFF002727)
    val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
    val primaryContainerLightHighContrast = Color(0xFF004B4B)
    val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val secondaryLightHighContrast = Color(0xFF0C2626)
    val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
    val secondaryContainerLightHighContrast = Color(0xFF2E4747)
    val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryLightHighContrast = Color(0xFF0C233C)
    val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
    val tertiaryContainerLightHighContrast = Color(0xFF2F445F)
    val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
    val errorLightHighContrast = Color(0xFF4E0002)
    val onErrorLightHighContrast = Color(0xFFFFFFFF)
    val errorContainerLightHighContrast = Color(0xFF8C0009)
    val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
    val backgroundLightHighContrast = Color(0xFFF4FBFA)
    val onBackgroundLightHighContrast = Color(0xFF161D1D)
    val surfaceLightHighContrast = Color(0xFFF4FBFA)
    val onSurfaceLightHighContrast = Color(0xFF000000)
    val surfaceVariantLightHighContrast = Color(0xFFDAE5E4)
    val onSurfaceVariantLightHighContrast = Color(0xFF1C2625)
    val outlineLightHighContrast = Color(0xFF3B4544)
    val outlineVariantLightHighContrast = Color(0xFF3B4544)
    val scrimLightHighContrast = Color(0xFF000000)
    val inverseSurfaceLightHighContrast = Color(0xFF2B3231)
    val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
    val inversePrimaryLightHighContrast = Color(0xFFA6FBFA)
    val surfaceDimLightHighContrast = Color(0xFFD5DBDA)
    val surfaceBrightLightHighContrast = Color(0xFFF4FBFA)
    val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
    val surfaceContainerLowLightHighContrast = Color(0xFFEFF5F4)
    val surfaceContainerLightHighContrast = Color(0xFFE9EFEE)
    val surfaceContainerHighLightHighContrast = Color(0xFFE3E9E9)
    val surfaceContainerHighestLightHighContrast = Color(0xFFDDE4E3)

    val primaryDark = Color(0xFF80D5D4)
    val onPrimaryDark = Color(0xFF003737)
    val primaryContainerDark = Color(0xFF004F50)
    val onPrimaryContainerDark = Color(0xFF9CF1F0)
    val secondaryDark = Color(0xFFB0CCCB)
    val onSecondaryDark = Color(0xFF1B3534)
    val secondaryContainerDark = Color(0xFF324B4B)
    val onSecondaryContainerDark = Color(0xFFCCE8E7)
    val tertiaryDark = Color(0xFFB3C8E8)
    val onTertiaryDark = Color(0xFF1C314B)
    val tertiaryContainerDark = Color(0xFF334863)
    val onTertiaryContainerDark = Color(0xFFD3E4FF)
    val errorDark = Color(0xFFFFB4AB)
    val onErrorDark = Color(0xFF690005)
    val errorContainerDark = Color(0xFF93000A)
    val onErrorContainerDark = Color(0xFFFFDAD6)
    val backgroundDark = Color(0xFF0E1514)
    val onBackgroundDark = Color(0xFFDDE4E3)
    val surfaceDark = Color(0xFF0E1514)
    val onSurfaceDark = Color(0xFFDDE4E3)
    val surfaceVariantDark = Color(0xFF3F4948)
    val onSurfaceVariantDark = Color(0xFFBEC9C8)
    val outlineDark = Color(0xFF889392)
    val outlineVariantDark = Color(0xFF3F4948)
    val scrimDark = Color(0xFF000000)
    val inverseSurfaceDark = Color(0xFFDDE4E3)
    val inverseOnSurfaceDark = Color(0xFF2B3231)
    val inversePrimaryDark = Color(0xFF006A6A)
    val surfaceDimDark = Color(0xFF0E1514)
    val surfaceBrightDark = Color(0xFF343A3A)
    val surfaceContainerLowestDark = Color(0xFF090F0F)
    val surfaceContainerLowDark = Color(0xFF161D1D)
    val surfaceContainerDark = Color(0xFF1A2121)
    val surfaceContainerHighDark = Color(0xFF252B2B)
    val surfaceContainerHighestDark = Color(0xFF2F3636)

    val primaryDarkMediumContrast = Color(0xFF84D9D8)
    val onPrimaryDarkMediumContrast = Color(0xFF001A1A)
    val primaryContainerDarkMediumContrast = Color(0xFF479E9D)
    val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
    val secondaryDarkMediumContrast = Color(0xFFB5D0CF)
    val onSecondaryDarkMediumContrast = Color(0xFF001A1A)
    val secondaryContainerDarkMediumContrast = Color(0xFF7B9695)
    val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
    val tertiaryDarkMediumContrast = Color(0xFFB7CCED)
    val onTertiaryDarkMediumContrast = Color(0xFF00172F)
    val tertiaryContainerDarkMediumContrast = Color(0xFF7D92B1)
    val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
    val errorDarkMediumContrast = Color(0xFFFFBAB1)
    val onErrorDarkMediumContrast = Color(0xFF370001)
    val errorContainerDarkMediumContrast = Color(0xFFFF5449)
    val onErrorContainerDarkMediumContrast = Color(0xFF000000)
    val backgroundDarkMediumContrast = Color(0xFF0E1514)
    val onBackgroundDarkMediumContrast = Color(0xFFDDE4E3)
    val surfaceDarkMediumContrast = Color(0xFF0E1514)
    val onSurfaceDarkMediumContrast = Color(0xFFF6FCFB)
    val surfaceVariantDarkMediumContrast = Color(0xFF3F4948)
    val onSurfaceVariantDarkMediumContrast = Color(0xFFC2CDCC)
    val outlineDarkMediumContrast = Color(0xFF9BA5A4)
    val outlineVariantDarkMediumContrast = Color(0xFF7B8585)
    val scrimDarkMediumContrast = Color(0xFF000000)
    val inverseSurfaceDarkMediumContrast = Color(0xFFDDE4E3)
    val inverseOnSurfaceDarkMediumContrast = Color(0xFF252B2B)
    val inversePrimaryDarkMediumContrast = Color(0xFF005151)
    val surfaceDimDarkMediumContrast = Color(0xFF0E1514)
    val surfaceBrightDarkMediumContrast = Color(0xFF343A3A)
    val surfaceContainerLowestDarkMediumContrast = Color(0xFF090F0F)
    val surfaceContainerLowDarkMediumContrast = Color(0xFF161D1D)
    val surfaceContainerDarkMediumContrast = Color(0xFF1A2121)
    val surfaceContainerHighDarkMediumContrast = Color(0xFF252B2B)
    val surfaceContainerHighestDarkMediumContrast = Color(0xFF2F3636)

    val primaryDarkHighContrast = Color(0xFFEAFFFE)
    val onPrimaryDarkHighContrast = Color(0xFF000000)
    val primaryContainerDarkHighContrast = Color(0xFF84D9D8)
    val onPrimaryContainerDarkHighContrast = Color(0xFF000000)
    val secondaryDarkHighContrast = Color(0xFFEAFFFE)
    val onSecondaryDarkHighContrast = Color(0xFF000000)
    val secondaryContainerDarkHighContrast = Color(0xFFB5D0CF)
    val onSecondaryContainerDarkHighContrast = Color(0xFF000000)
    val tertiaryDarkHighContrast = Color(0xFFFAFAFF)
    val onTertiaryDarkHighContrast = Color(0xFF000000)
    val tertiaryContainerDarkHighContrast = Color(0xFFB7CCED)
    val onTertiaryContainerDarkHighContrast = Color(0xFF000000)
    val errorDarkHighContrast = Color(0xFFFFF9F9)
    val onErrorDarkHighContrast = Color(0xFF000000)
    val errorContainerDarkHighContrast = Color(0xFFFFBAB1)
    val onErrorContainerDarkHighContrast = Color(0xFF000000)
    val backgroundDarkHighContrast = Color(0xFF0E1514)
    val onBackgroundDarkHighContrast = Color(0xFFDDE4E3)
    val surfaceDarkHighContrast = Color(0xFF0E1514)
    val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
    val surfaceVariantDarkHighContrast = Color(0xFF3F4948)
    val onSurfaceVariantDarkHighContrast = Color(0xFFF3FDFC)
    val outlineDarkHighContrast = Color(0xFFC2CDCC)
    val outlineVariantDarkHighContrast = Color(0xFFC2CDCC)
    val scrimDarkHighContrast = Color(0xFF000000)
    val inverseSurfaceDarkHighContrast = Color(0xFFDDE4E3)
    val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
    val inversePrimaryDarkHighContrast = Color(0xFF003030)
    val surfaceDimDarkHighContrast = Color(0xFF0E1514)
    val surfaceBrightDarkHighContrast = Color(0xFF343A3A)
    val surfaceContainerLowestDarkHighContrast = Color(0xFF090F0F)
    val surfaceContainerLowDarkHighContrast = Color(0xFF161D1D)
    val surfaceContainerDarkHighContrast = Color(0xFF1A2121)
    val surfaceContainerHighDarkHighContrast = Color(0xFF252B2B)
    val surfaceContainerHighestDarkHighContrast = Color(0xFF2F3636)


    val lightScheme = lightColorScheme(
        primary = primaryLight,
        onPrimary = onPrimaryLight,
        primaryContainer = primaryContainerLight,
        onPrimaryContainer = onPrimaryContainerLight,
        secondary = secondaryLight,
        onSecondary = onSecondaryLight,
        secondaryContainer = secondaryContainerLight,
        onSecondaryContainer = onSecondaryContainerLight,
        tertiary = tertiaryLight,
        onTertiary = onTertiaryLight,
        tertiaryContainer = tertiaryContainerLight,
        onTertiaryContainer = onTertiaryContainerLight,
        error = errorLight,
        onError = onErrorLight,
        errorContainer = errorContainerLight,
        onErrorContainer = onErrorContainerLight,
        background = backgroundLight,
        onBackground = onBackgroundLight,
        surface = surfaceLight,
        onSurface = onSurfaceLight,
        surfaceVariant = surfaceVariantLight,
        onSurfaceVariant = onSurfaceVariantLight,
        outline = outlineLight,
        outlineVariant = outlineVariantLight,
        scrim = scrimLight,
        inverseSurface = inverseSurfaceLight,
        inverseOnSurface = inverseOnSurfaceLight,
        inversePrimary = inversePrimaryLight,
        surfaceDim = surfaceDimLight,
        surfaceBright = surfaceBrightLight,
        surfaceContainerLowest = surfaceContainerLowestLight,
        surfaceContainerLow = surfaceContainerLowLight,
        surfaceContainer = surfaceContainerLight,
        surfaceContainerHigh = surfaceContainerHighLight,
        surfaceContainerHighest = surfaceContainerHighestLight,
    )

    val darkScheme = darkColorScheme(
        primary = primaryDark,
        onPrimary = onPrimaryDark,
        primaryContainer = primaryContainerDark,
        onPrimaryContainer = onPrimaryContainerDark,
        secondary = secondaryDark,
        onSecondary = onSecondaryDark,
        secondaryContainer = secondaryContainerDark,
        onSecondaryContainer = onSecondaryContainerDark,
        tertiary = tertiaryDark,
        onTertiary = onTertiaryDark,
        tertiaryContainer = tertiaryContainerDark,
        onTertiaryContainer = onTertiaryContainerDark,
        error = errorDark,
        onError = onErrorDark,
        errorContainer = errorContainerDark,
        onErrorContainer = onErrorContainerDark,
        background = backgroundDark,
        onBackground = onBackgroundDark,
        surface = surfaceDark,
        onSurface = onSurfaceDark,
        surfaceVariant = surfaceVariantDark,
        onSurfaceVariant = onSurfaceVariantDark,
        outline = outlineDark,
        outlineVariant = outlineVariantDark,
        scrim = scrimDark,
        inverseSurface = inverseSurfaceDark,
        inverseOnSurface = inverseOnSurfaceDark,
        inversePrimary = inversePrimaryDark,
        surfaceDim = surfaceDimDark,
        surfaceBright = surfaceBrightDark,
        surfaceContainerLowest = surfaceContainerLowestDark,
        surfaceContainerLow = surfaceContainerLowDark,
        surfaceContainer = surfaceContainerDark,
        surfaceContainerHigh = surfaceContainerHighDark,
        surfaceContainerHighest = surfaceContainerHighestDark,
    )

    val mediumContrastLightColorScheme = lightColorScheme(
        primary = primaryLightMediumContrast,
        onPrimary = onPrimaryLightMediumContrast,
        primaryContainer = primaryContainerLightMediumContrast,
        onPrimaryContainer = onPrimaryContainerLightMediumContrast,
        secondary = secondaryLightMediumContrast,
        onSecondary = onSecondaryLightMediumContrast,
        secondaryContainer = secondaryContainerLightMediumContrast,
        onSecondaryContainer = onSecondaryContainerLightMediumContrast,
        tertiary = tertiaryLightMediumContrast,
        onTertiary = onTertiaryLightMediumContrast,
        tertiaryContainer = tertiaryContainerLightMediumContrast,
        onTertiaryContainer = onTertiaryContainerLightMediumContrast,
        error = errorLightMediumContrast,
        onError = onErrorLightMediumContrast,
        errorContainer = errorContainerLightMediumContrast,
        onErrorContainer = onErrorContainerLightMediumContrast,
        background = backgroundLightMediumContrast,
        onBackground = onBackgroundLightMediumContrast,
        surface = surfaceLightMediumContrast,
        onSurface = onSurfaceLightMediumContrast,
        surfaceVariant = surfaceVariantLightMediumContrast,
        onSurfaceVariant = onSurfaceVariantLightMediumContrast,
        outline = outlineLightMediumContrast,
        outlineVariant = outlineVariantLightMediumContrast,
        scrim = scrimLightMediumContrast,
        inverseSurface = inverseSurfaceLightMediumContrast,
        inverseOnSurface = inverseOnSurfaceLightMediumContrast,
        inversePrimary = inversePrimaryLightMediumContrast,
        surfaceDim = surfaceDimLightMediumContrast,
        surfaceBright = surfaceBrightLightMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestLightMediumContrast,
        surfaceContainerLow = surfaceContainerLowLightMediumContrast,
        surfaceContainer = surfaceContainerLightMediumContrast,
        surfaceContainerHigh = surfaceContainerHighLightMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestLightMediumContrast,
    )

    val highContrastLightColorScheme = lightColorScheme(
        primary = primaryLightHighContrast,
        onPrimary = onPrimaryLightHighContrast,
        primaryContainer = primaryContainerLightHighContrast,
        onPrimaryContainer = onPrimaryContainerLightHighContrast,
        secondary = secondaryLightHighContrast,
        onSecondary = onSecondaryLightHighContrast,
        secondaryContainer = secondaryContainerLightHighContrast,
        onSecondaryContainer = onSecondaryContainerLightHighContrast,
        tertiary = tertiaryLightHighContrast,
        onTertiary = onTertiaryLightHighContrast,
        tertiaryContainer = tertiaryContainerLightHighContrast,
        onTertiaryContainer = onTertiaryContainerLightHighContrast,
        error = errorLightHighContrast,
        onError = onErrorLightHighContrast,
        errorContainer = errorContainerLightHighContrast,
        onErrorContainer = onErrorContainerLightHighContrast,
        background = backgroundLightHighContrast,
        onBackground = onBackgroundLightHighContrast,
        surface = surfaceLightHighContrast,
        onSurface = onSurfaceLightHighContrast,
        surfaceVariant = surfaceVariantLightHighContrast,
        onSurfaceVariant = onSurfaceVariantLightHighContrast,
        outline = outlineLightHighContrast,
        outlineVariant = outlineVariantLightHighContrast,
        scrim = scrimLightHighContrast,
        inverseSurface = inverseSurfaceLightHighContrast,
        inverseOnSurface = inverseOnSurfaceLightHighContrast,
        inversePrimary = inversePrimaryLightHighContrast,
        surfaceDim = surfaceDimLightHighContrast,
        surfaceBright = surfaceBrightLightHighContrast,
        surfaceContainerLowest = surfaceContainerLowestLightHighContrast,
        surfaceContainerLow = surfaceContainerLowLightHighContrast,
        surfaceContainer = surfaceContainerLightHighContrast,
        surfaceContainerHigh = surfaceContainerHighLightHighContrast,
        surfaceContainerHighest = surfaceContainerHighestLightHighContrast,
    )

    val mediumContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkMediumContrast,
        onPrimary = onPrimaryDarkMediumContrast,
        primaryContainer = primaryContainerDarkMediumContrast,
        onPrimaryContainer = onPrimaryContainerDarkMediumContrast,
        secondary = secondaryDarkMediumContrast,
        onSecondary = onSecondaryDarkMediumContrast,
        secondaryContainer = secondaryContainerDarkMediumContrast,
        onSecondaryContainer = onSecondaryContainerDarkMediumContrast,
        tertiary = tertiaryDarkMediumContrast,
        onTertiary = onTertiaryDarkMediumContrast,
        tertiaryContainer = tertiaryContainerDarkMediumContrast,
        onTertiaryContainer = onTertiaryContainerDarkMediumContrast,
        error = errorDarkMediumContrast,
        onError = onErrorDarkMediumContrast,
        errorContainer = errorContainerDarkMediumContrast,
        onErrorContainer = onErrorContainerDarkMediumContrast,
        background = backgroundDarkMediumContrast,
        onBackground = onBackgroundDarkMediumContrast,
        surface = surfaceDarkMediumContrast,
        onSurface = onSurfaceDarkMediumContrast,
        surfaceVariant = surfaceVariantDarkMediumContrast,
        onSurfaceVariant = onSurfaceVariantDarkMediumContrast,
        outline = outlineDarkMediumContrast,
        outlineVariant = outlineVariantDarkMediumContrast,
        scrim = scrimDarkMediumContrast,
        inverseSurface = inverseSurfaceDarkMediumContrast,
        inverseOnSurface = inverseOnSurfaceDarkMediumContrast,
        inversePrimary = inversePrimaryDarkMediumContrast,
        surfaceDim = surfaceDimDarkMediumContrast,
        surfaceBright = surfaceBrightDarkMediumContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkMediumContrast,
        surfaceContainerLow = surfaceContainerLowDarkMediumContrast,
        surfaceContainer = surfaceContainerDarkMediumContrast,
        surfaceContainerHigh = surfaceContainerHighDarkMediumContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkMediumContrast,
    )

    val highContrastDarkColorScheme = darkColorScheme(
        primary = primaryDarkHighContrast,
        onPrimary = onPrimaryDarkHighContrast,
        primaryContainer = primaryContainerDarkHighContrast,
        onPrimaryContainer = onPrimaryContainerDarkHighContrast,
        secondary = secondaryDarkHighContrast,
        onSecondary = onSecondaryDarkHighContrast,
        secondaryContainer = secondaryContainerDarkHighContrast,
        onSecondaryContainer = onSecondaryContainerDarkHighContrast,
        tertiary = tertiaryDarkHighContrast,
        onTertiary = onTertiaryDarkHighContrast,
        tertiaryContainer = tertiaryContainerDarkHighContrast,
        onTertiaryContainer = onTertiaryContainerDarkHighContrast,
        error = errorDarkHighContrast,
        onError = onErrorDarkHighContrast,
        errorContainer = errorContainerDarkHighContrast,
        onErrorContainer = onErrorContainerDarkHighContrast,
        background = backgroundDarkHighContrast,
        onBackground = onBackgroundDarkHighContrast,
        surface = surfaceDarkHighContrast,
        onSurface = onSurfaceDarkHighContrast,
        surfaceVariant = surfaceVariantDarkHighContrast,
        onSurfaceVariant = onSurfaceVariantDarkHighContrast,
        outline = outlineDarkHighContrast,
        outlineVariant = outlineVariantDarkHighContrast,
        scrim = scrimDarkHighContrast,
        inverseSurface = inverseSurfaceDarkHighContrast,
        inverseOnSurface = inverseOnSurfaceDarkHighContrast,
        inversePrimary = inversePrimaryDarkHighContrast,
        surfaceDim = surfaceDimDarkHighContrast,
        surfaceBright = surfaceBrightDarkHighContrast,
        surfaceContainerLowest = surfaceContainerLowestDarkHighContrast,
        surfaceContainerLow = surfaceContainerLowDarkHighContrast,
        surfaceContainer = surfaceContainerDarkHighContrast,
        surfaceContainerHigh = surfaceContainerHighDarkHighContrast,
        surfaceContainerHighest = surfaceContainerHighestDarkHighContrast,
    )
}
